version: '3.8'
services:
  dev-db:
    image: postgres:14
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: learn-material
    volumes:
      - ./postgres-data:/var/lib/postgresql

