version: '3.8'
services:
  dev-db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: learnMaterial
    volumes:
      - ./postgres-data:/var/lib/postgresql

